spring.application.name=pio-pix-auth-server
spring.datasource.url=jdbc:postgresql://db:5432/pio-pix
spring.datasource.username=pio_user
spring.datasource.password=pio_user
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8080
logging.level.pro.sky.pio_pix_auth_server=TRACE
